I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 53, in script
    image user0 = img
  File "game/script.rpy", line 53, in script
    image user0 = img
  File "game/script.rpy", line 53, in <module>
    image user0 = img
NameError: name 'img' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 53, in script
    image user0 = img
  File "game/script.rpy", line 53, in script
    image user0 = img
  File "renpy/ast.py", line 1027, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 53, in <module>
    image user0 = img
NameError: name 'img' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Da Capo 1.0
Mon Jan  3 12:54:44 2022
