I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ch6.rpy", line 57, in script
    st "你...你...你......，怎麼可能......？\n啊啊啊啊啊啊！！！！！！"
Exception: Sayer 'st' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ch6.rpy", line 57, in script
    st "你...你...你......，怎麼可能......？\n啊啊啊啊啊啊！！！！！！"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'st' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Da Capo 1.0
Tue Jan 11 21:53:43 2022
